In [6]:
import pandas as pd
import numpy as np

df = pd.read_csv("insurance_data.csv")
print(df.head())

print("Dataset Info:")
df.info()

print("Descriptive Statistics:")
print(df.describe())

df.fillna("Unknown", inplace=True)

df['TXN_DATE_TIME'] = pd.to_datetime(df['TXN_DATE_TIME'], errors='coerce')

df.drop_duplicates(subset=['TRANSACTION_ID'], inplace=True)

bins = [0, 5000, 10000, 20000, 30000, 40000, 50000, 60000, 70000, 80000, 90000, 100000]
labels = ['Under 5k', '5k to 10k', '10k to 20k', '20k to 30k', '30k to 40k', '40k to 50k', 
          '50k to 60k', '60k to 70k', '70k to 80k', '80k to 90k', '90k to 100k']

df['Claim Amount Bins'] = pd.cut(df['CLAIM_AMOUNT'], bins=bins, labels=labels, include_lowest=True)

claim_distribution = df['Claim Amount Bins'].value_counts()
print('Claim distribution:'+ str(claim_distribution))

correlation = df[['CLAIM_AMOUNT', 'PREMIUM_AMOUNT']].corr()
correlation_value = correlation.loc['CLAIM_AMOUNT', 'PREMIUM_AMOUNT']
print('Correlation coefficient: ' + str(correlation_value))

df.to_csv("cleaned_insurance_data.csv", index=False)

         TXN_DATE_TIME TRANSACTION_ID CUSTOMER_ID POLICY_NUMBER POLICY_EFF_DT  \
0  2020-06-01 00:00:00    TXN00000001   A00003822   PLC00008468    2015-06-23
1  2020-06-01 00:00:00    TXN00000002   A00008149   PLC00009594    2018-04-21
2  2020-06-01 00:00:00    TXN00000003   A00003172   PLC00007969    2019-10-03
3  2020-06-01 00:00:00    TXN00000004   A00007572   PLC00009292    2016-11-29
4  2020-06-01 00:00:00    TXN00000005   A00008173   PLC00000204    2011-12-26

      LOSS_DT   REPORT_DT INSURANCE_TYPE  PREMIUM_AMOUNT  CLAIM_AMOUNT  ...  \
0  2020-05-16  2020-05-21         Health          157.13          9000  ...
1  2020-05-13  2020-05-18       Property          141.71         26000  ...
2  2020-05-21  2020-05-26       Property          157.24         13000  ...
3  2020-05-14  2020-05-19         Health          172.87         16000  ...
4  2020-05-17  2020-05-22         Travel           88.53          3000  ...

  CLAIM_STATUS INCIDENT_SEVERITY AUTHORITY_CONTACTED ANY_INJURY  \
0            A        Major Loss              Police          0
1            A        Total Loss           Ambulance          1
2            A        Total Loss              Police          0
3            A        Minor Loss           Ambulance          0
4            A        Major Loss              Police          0

  POLICE_REPORT_AVAILABLE  INCIDENT_STATE   INCIDENT_CITY  \
0                       1              GA        Savannah
1                       0              AL      Montgomery
2                       1              CO  Grand Junction
3                       0              GA        Savannah
4                       1              TN       Nashville

  INCIDENT_HOUR_OF_THE_DAY    AGENT_ID  VENDOR_ID
0                        4  AGENT00413  VNDR00556
1                        0  AGENT00769  VNDR00592
2                       19  AGENT00883  VNDR00031
3                       12  AGENT00278  VNDR00075
4                       18  AGENT00636  VNDR00472

[5 rows x 38 columns]
Dataset Info:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 38 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   TXN_DATE_TIME             10000 non-null  object
 1   TRANSACTION_ID            10000 non-null  object
 2   CUSTOMER_ID               10000 non-null  object
 3   POLICY_NUMBER             10000 non-null  object
 4   POLICY_EFF_DT             10000 non-null  object
 5   LOSS_DT                   10000 non-null  object
 6   REPORT_DT                 10000 non-null  object
 7   INSURANCE_TYPE            10000 non-null  object
 8   PREMIUM_AMOUNT            10000 non-null  float64
 9   CLAIM_AMOUNT              10000 non-null  int64
 10  CUSTOMER_NAME             10000 non-null  object
 11  ADDRESS_LINE1             10000 non-null  object
 12  ADDRESS_LINE2             1495 non-null   object
 13  CITY                      9946 non-null   object
 14  STATE                     10000 non-null  object
 15  POSTAL_CODE               10000 non-null  int64
 16  SSN                       10000 non-null  object
 17  MARITAL_STATUS            10000 non-null  object
 18  AGE                       10000 non-null  int64
 19  TENURE                    10000 non-null  int64
 20  EMPLOYMENT_STATUS         10000 non-null  object
 21  NO_OF_FAMILY_MEMBERS      10000 non-null  int64
 22  RISK_SEGMENTATION         10000 non-null  object
 23  HOUSE_TYPE                10000 non-null  object
 24  SOCIAL_CLASS              10000 non-null  object
 25  ROUTING_NUMBER            10000 non-null  int64
 26  ACCT_NUMBER               10000 non-null  object
 27  CUSTOMER_EDUCATION_LEVEL  9471 non-null   object
 28  CLAIM_STATUS              10000 non-null  object
 29  INCIDENT_SEVERITY         10000 non-null  object
 30  AUTHORITY_CONTACTED       8055 non-null   object
 31  ANY_INJURY                10000 non-null  int64
 32  POLICE_REPORT_AVAILABLE   10000 non-null  int64
 33  INCIDENT_STATE            10000 non-null  object
 34  INCIDENT_CITY             9954 non-null   object
 35  INCIDENT_HOUR_OF_THE_DAY  10000 non-null  int64
 36  AGENT_ID                  10000 non-null  object
 37  VENDOR_ID                 6755 non-null   object
dtypes: float64(1), int64(9), object(28)
memory usage: 2.9+ MB
Descriptive Statistics:
       PREMIUM_AMOUNT   CLAIM_AMOUNT   POSTAL_CODE           AGE  \
count    10000.000000   10000.000000  10000.000000  10000.000000
mean        88.508595   16563.830000  48288.830500     44.466100
std         48.315874   22037.489735  32467.389801     11.516827
min          6.000000     100.000000   1001.000000     25.000000
25%         62.015000    2000.000000  21061.000000     34.000000
50%         88.835000    7000.000000  37206.000000     45.000000
75%        121.902500   21000.000000  80004.000000     54.000000
max        200.000000  100000.000000  99669.000000     64.000000

             TENURE  NO_OF_FAMILY_MEMBERS  ROUTING_NUMBER    ANY_INJURY  \
count  10000.000000          10000.000000    1.000000e+04  10000.000000
mean      62.949800              4.488400    7.052882e+07      0.699100
std       32.890604              1.712588    3.451879e+07      0.458672
min        6.000000              2.000000    1.000074e+07      0.000000
25%       34.000000              3.000000    4.071761e+07      0.000000
50%       64.000000              4.000000    7.036614e+07      1.000000
75%       92.000000              6.000000    1.000638e+08      1.000000
max      119.000000              7.000000    1.299981e+08      1.000000

       POLICE_REPORT_AVAILABLE  INCIDENT_HOUR_OF_THE_DAY
count             10000.000000              10000.000000
mean                  0.692800                 11.604000
std                   0.461356                  6.877101
min                   0.000000                  0.000000
25%                   0.000000                  6.000000
50%                   1.000000                 12.000000
75%                   1.000000                 18.000000
max                   1.000000                 23.000000
Claim distribution:Claim Amount Bins
Under 5k       4564
10k to 20k     1642
5k to 10k      1267
30k to 40k      720
20k to 30k      697
40k to 50k      209
50k to 60k      189
70k to 80k      187
60k to 70k      181
80k to 90k      174
90k to 100k     170
Name: count, dtype: int64
Correlation coefficient: 0.10921007837196214